/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 keycap_m.gltf 
*/

import {useGLTF} from '@react-three/drei'
import BaseKeycap from "./BaseKeycap";


export default function Keycap({basePosition, scaleAmp, text, func, ...props}) {
    const {nodes, materials} = useGLTF(`${process.env.PUBLIC_URL}/keycap/keycap_m.gltf`)

    return (
        <BaseKeycap basePosition={basePosition}
                    scaleAmp={scaleAmp}
                    text={text}
                    func={func}
                    {...props}>
            <mesh
                geometry={nodes.Cube.geometry}
                material={materials.Material}/>
        </BaseKeycap>
    )
}

useGLTF.preload(`${process.env.PUBLIC_URL}/keycap/keycap_m.gltf`)
